// <auto-generated />
namespace IRS.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SP_DemoMaster_list : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SP_DemoMaster_list));
        
        string IMigrationMetadata.Id
        {
            get { return "201609121316206_SP_DemoMaster_list"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
